import { 
  Stethoscope, 
  User, 
  Calendar, 
  FileText, 
  ShieldCheck, 
  Building, 
  Bell, 
  Menu, 
  X,
  Home,
  AlertCircle,
  CheckCircle,
  Clock,
  ArrowRight,
  ArrowLeft,
  Plus,
  Search,
  Star,
  MapPin,
  Flame,
  UploadCloud,
  QrCode,
  Eye,
  EyeOff,
  Phone,
  Heart,
  Trash2
} from 'lucide-react';

export {
  Stethoscope as StethoscopeIcon,
  User as UserIcon,
  Calendar as CalendarIcon,
  FileText as FileTextIcon,
  ShieldCheck as ShieldCheckIcon,
  Building as BuildingIcon,
  Bell as BellIcon,
  Menu as MenuIcon,
  X as XIcon,
  Home as HomeIcon,
  AlertCircle as AlertCircleIcon,
  CheckCircle as CheckCircleIcon,
  Clock as ClockIcon,
  ArrowRight as ArrowRightIcon,
  ArrowLeft as ArrowLeftIcon,
  Plus as PlusIcon,
  Search as SearchIcon,
  Star as StarIcon,
  MapPin as MapPinIcon,
  Flame as FlameIcon,
  UploadCloud as UploadCloudIcon,
  QrCode as QrCodeIcon,
  Eye as EyeIcon,
  EyeOff as EyeOffIcon,
  Phone as PhoneIcon,
  Heart as HeartIcon,
  Trash2 as TrashIcon,
};
